services:
  web:
    container_name: php-apache
    image: my-crud-web
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./www:/var/www/html/
    ports:
      - "8082:80"
    environment:
      - LANG=en_US.utf8
    depends_on:
      - db

  db:
    container_name: db
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: raspberrypi
      MYSQL_PASSWORD: 12345
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d
    ports:
      - "9906:3306"
